name: geodispatch

networks:
  geodispatch-net:
    driver: bridge

include:
  - agent/docker-compose.yml
  - supervisor/docker-compose.yml
  - dashboard/docker-compose.yml
  - mock-camara/docker-compose.yml