name: geodispatch

networks:
  default:
    name: geodispatch-net

include:
  - agent/docker-compose.yml
  - supervisor/docker-compose.dev.yml
  # - dashboard/docker-compose.yml
  # - mock-camara/docker-compose.yml